# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import quilt_pb2 as quilt__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quilt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HomeDatastoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHomeDatastoreSystem = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/GetHomeDatastoreSystem',
                request_serializer=quilt__pb2.GetHomeDatastoreSystemRequest.SerializeToString,
                response_deserializer=quilt__pb2.HomeDatastoreSystem.FromString,
                _registered_method=True)
        self.UpdateComfortSetting = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateComfortSetting',
                request_serializer=quilt__pb2.UpdateComfortSettingRequest.SerializeToString,
                response_deserializer=quilt__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.UpdateSpace = channel.unary_unary(
                '/core.protos.home_datastore.HomeDatastoreService/UpdateSpace',
                request_serializer=quilt__pb2.UpdateSpaceRequest.SerializeToString,
                response_deserializer=quilt__pb2.UpdateResponse.FromString,
                _registered_method=True)


class HomeDatastoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHomeDatastoreSystem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateComfortSetting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HomeDatastoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHomeDatastoreSystem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHomeDatastoreSystem,
                    request_deserializer=quilt__pb2.GetHomeDatastoreSystemRequest.FromString,
                    response_serializer=quilt__pb2.HomeDatastoreSystem.SerializeToString,
            ),
            'UpdateComfortSetting': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateComfortSetting,
                    request_deserializer=quilt__pb2.UpdateComfortSettingRequest.FromString,
                    response_serializer=quilt__pb2.UpdateResponse.SerializeToString,
            ),
            'UpdateSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSpace,
                    request_deserializer=quilt__pb2.UpdateSpaceRequest.FromString,
                    response_serializer=quilt__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.protos.home_datastore.HomeDatastoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('core.protos.home_datastore.HomeDatastoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HomeDatastoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHomeDatastoreSystem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/GetHomeDatastoreSystem',
            quilt__pb2.GetHomeDatastoreSystemRequest.SerializeToString,
            quilt__pb2.HomeDatastoreSystem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateComfortSetting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateComfortSetting',
            quilt__pb2.UpdateComfortSettingRequest.SerializeToString,
            quilt__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/core.protos.home_datastore.HomeDatastoreService/UpdateSpace',
            quilt__pb2.UpdateSpaceRequest.SerializeToString,
            quilt__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
